[
  {
    color: "#6666ff",
    date: "2024-03-05T05:00:00.000Z",
    id: 35,
    text: "Shopping",
    username: "Noah",
    value: 30,
  },
  {
    color: "#6666ff",
    date: "2024-03-05T05:00:00.000Z",
    id: 36,
    text: "Shopping",
    username: "Noah",
    value: 300,
  },
  {
    color: "#6666ff",
    date: "2024-03-05T05:00:00.000Z",
    id: 37,
    text: "Shopping",
    username: "Noah",
    value: 50,
  },
  {
    color: "#6666ff",
    date: "2024-03-05T05:00:00.000Z",
    id: 38,
    text: "Shopping",
    username: "Noah",
    value: 20,
  },
];

[
  {
    category: "Shopping",
    color: "#6666ff",
    iconname: "basket-shopping",
    icontype: "FontAwesome6",
    id: 1,
    username: "Noah",
  },
  {
    category: "Money",
    color: "#ff0000",
    iconname: "wallet",
    icontype: "FontAwesome6",
    id: 2,
    username: "Noah",
  },
  {
    category: "toll",
    color: "#339933",
    iconname: "bus-simple",
    icontype: "FontAwesome6",
    id: 3,
    username: "Noah",
  },
  {
    category: "Fly",
    color: "#ff0000",
    iconname: "plane",
    icontype: "FontAwesome6",
    id: 4,
    username: "Noah",
  },
  {
    category: "Test",
    color: "#8b4513",
    iconname: "chart-line",
    icontype: "FontAwesome6",
    id: 5,
    username: "Noah",
  },
  {
    category: "Learning",
    color: "#0000ff",
    iconname: "graduation-cap",
    icontype: "FontAwesome6",
    id: 6,
    username: "Noah",
  },
  {
    category: "Savings",
    color: "#ffd700",
    iconname: "piggy-bank",
    icontype: "FontAwesome6",
    id: 7,
    username: "Noah",
  },
];
