POST http://localhost:3000/add
Content-Type: application/json

{
    "username": "Noah",
    "text": "Travel",
    "value": 550,
    "color": "#a83254",
    "date": "2024-02-29"
}

###
GET http://localhost:3000/expenses/Joann
Content-Type: application/json

###
POST http://localhost:3000/catagory
Content-Type: application/json

{
    "username": "Noah",
    "category": "Shopping",
    "iconname": "basket-shopping",
    "icontype": "FontAwesome6",
    "color": "#6666ff"
}

###
GET http://localhost:3000/catagory/Noah
Content-Type: application/json

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "nuoya1996@gmail.com",
    "password": "sr19960309"
}

###
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "nuoya1996@gmail.com",
    "password": "sr19960309"
}

###
POST http://localhost:3000/account
Content-Type: application/json

{
    "email": "nuoya1996@gmail.com",
    "name": "test_account2"
}

###
POST http://localhost:3000/request
Content-Type: application/json

{
    "account_id": "8",
    "shared_with_email": "joann@gmail.com"
}

###
GET http://localhost:3000/request/joann@gmail.com
Content-Type: application/json

###
POST http://localhost:3000/request/approve
Content-Type: application/json

{
    "requestId": 1
}



