const ICONS_DATA = [
  {
    groupName: "Finances",
    icons: [
      { type: "FontAwesome6", name: "wallet" },
      { type: "FontAwesome6", name: "coins" },
      { type: "FontAwesome6", name: "dollar-sign" },
      { type: "FontAwesome6", name: "piggy-bank" },
      { type: "FontAwesome6", name: "credit-card" },
      { type: "FontAwesome6", name: "calculator" },
      { type: "FontAwesome6", name: "money-check" },
      { type: "FontAwesome6", name: "chart-line" },
    ],
  },
  {
    groupName: "Transportation",
    icons: [
      { type: "FontAwesome6", name: "car" },
      { type: "FontAwesome6", name: "bus-simple" },
      { type: "FontAwesome6", name: "train" },
      { type: "FontAwesome6", name: "bicycle" },
      { type: "FontAwesome6", name: "taxi" },
      { type: "FontAwesome6", name: "motorcycle" },
      { type: "FontAwesome6", name: "plane" },
      { type: "FontAwesome6", name: "ship" },
      { type: "FontAwesome6", name: "train-subway" },
      { type: "FontAwesome6", name: "truck" },
    ],
  },
  {
    groupName: "Shopping",
    icons: [
      { type: "FontAwesome6", name: "cart-shopping" },
      { type: "FontAwesome6", name: "bag-shopping" },
      { type: "FontAwesome6", name: "store" },
      { type: "FontAwesome6", name: "tags" },
      { type: "FontAwesome6", name: "tag" },
      { type: "FontAwesome6", name: "basket-shopping" },
      { type: "FontAwesome6", name: "barcode" },
      { type: "FontAwesome6", name: "cash-register" },
      { type: "FontAwesome6", name: "shop" },
      { type: "FontAwesome6", name: "percent" },
    ],
  },
  {
    groupName: "Food",
    icons: [
      { type: "FontAwesome6", name: "utensils" },
      { type: "FontAwesome6", name: "pizza-slice" },
      { type: "FontAwesome6", name: "burger" },
      { type: "FontAwesome6", name: "hotdog" },
      { type: "FontAwesome6", name: "ice-cream" },
      { type: "FontAwesome6", name: "apple-whole" },
      { type: "FontAwesome6", name: "bread-slice" },
      { type: "FontAwesome6", name: "egg" },
      { type: "FontAwesome6", name: "wine-glass" },
      { type: "FontAwesome6", name: "bowl-food" },
    ],
  },
  {
    groupName: "Home",
    icons: [
      { type: "FontAwesome6", name: "house" },
      { type: "FontAwesome6", name: "key" },
      { type: "FontAwesome6", name: "door-closed" },
      { type: "FontAwesome6", name: "warehouse" },
      { type: "FontAwesome6", name: "bed" },
      { type: "FontAwesome6", name: "couch" },
      { type: "FontAwesome6", name: "lightbulb" },
      { type: "FontAwesome6", name: "plant-wilt" },
      { type: "FontAwesome6", name: "tv" },
      { type: "FontAwesome6", name: "shower" },
    ],
  },
  {
    groupName: "Health",
    icons: [
      { type: "FontAwesome6", name: "heart-circle-check" },
      { type: "FontAwesome6", name: "stethoscope" },
      { type: "FontAwesome6", name: "prescription-bottle-medical" },
      { type: "FontAwesome6", name: "hand-holding-medical" },
      { type: "FontAwesome6", name: "pills" },
      { type: "FontAwesome6", name: "bandage" },
      { type: "FontAwesome6", name: "thermometer" },
      { type: "FontAwesome6", name: "user-nurse" },
      { type: "FontAwesome6", name: "hospital" },
      { type: "FontAwesome6", name: "prescription-bottle" },
    ],
  },
  {
    groupName: "Beauty",
    icons: [
      { type: "FontAwesome6", name: "spray-can" },
      { type: "MaterialCommunityIcons", name: "lipstick" },
      { type: "MaterialCommunityIcons", name: "mirror" },
      { type: "MaterialCommunityIcons", name: "hair-dryer" },
      { type: "FontAwesome6", name: "spa" },
      { type: "FontAwesome6", name: "mask" },
      { type: "Entypo", name: "flat-brush" },
      { type: "FontAwesome6", name: "chair" },
    ],
  },
  {
    groupName: "Entertainment",
    icons: [
      { type: "FontAwesome6", name: "gamepad" },
      { type: "FontAwesome6", name: "film" },
      { type: "FontAwesome6", name: "music" },
      { type: "Ionicons", name: "ticket" },
      { type: "FontAwesome6", name: "tv" },
      { type: "FontAwesome6", name: "masks-theater" },
      { type: "FontAwesome6", name: "microphone" },
      { type: "FontAwesome6", name: "dice" },
      { type: "FontAwesome6", name: "puzzle-piece" },
      { type: "FontAwesome6", name: "camera" },
    ],
  },
  {
    groupName: "Accounts",
    icons: [
      { type: "FontAwesome6", name: "users" },
      { type: "FontAwesome6", name: "user" },
      { type: "FontAwesome6", name: "user-circle" },
      { type: "FontAwesome6", name: "user-tie" },
      { type: "FontAwesome6", name: "id-card" },
      { type: "FontAwesome6", name: "address-card" },
      { type: "FontAwesome6", name: "user-secret" },
      { type: "FontAwesome6", name: "passport" },
      { type: "FontAwesome6", name: "user-ninja" },
      { type: "FontAwesome6", name: "user-astronaut" },
    ],
  },
  {
    groupName: "Workout",
    icons: [
      { type: "FontAwesome6", name: "dumbbell" },
      { type: "FontAwesome6", name: "person-running" },
      { type: "FontAwesome6", name: "person-biking" },
      { type: "FontAwesome6", name: "weight-hanging" },
      { type: "FontAwesome6", name: "person-walking" },
      { type: "FontAwesome6", name: "person-swimming" },
      { type: "FontAwesome6", name: "basketball" },
      { type: "FontAwesome6", name: "soccer-ball" },
      { type: "FontAwesome6", name: "volleyball" },
      { type: "MaterialCommunityIcons", name: "yoga" },
    ],
  },
  {
    groupName: "Relaxation",
    icons: [
      { type: "FontAwesome6", name: "hot-tub-person" },
      { type: "FontAwesome6", name: "umbrella-beach" },
      { type: "FontAwesome6", name: "campground" },
      { type: "MaterialCommunityIcons", name: "glass-cocktail" },
      { type: "FontAwesome6", name: "guitar" },
      { type: "FontAwesome6", name: "book" },
      { type: "FontAwesome6", name: "headphones-alt" },
      { type: "MaterialCommunityIcons", name: "candle" },
      { type: "FontAwesome6", name: "music" },
      { type: "MaterialCommunityIcons", name: "sleep" },
    ],
  },
  {
    groupName: "Education",
    icons: [
      { type: "FontAwesome6", name: "graduation-cap" },
      { type: "FontAwesome6", name: "book-open" },
      { type: "FontAwesome6", name: "chalkboard-teacher" },
      { type: "FontAwesome6", name: "school" },
      { type: "FontAwesome6", name: "pen" },
      { type: "FontAwesome6", name: "lightbulb" },
      { type: "FontAwesome6", name: "microscope" },
      { type: "FontAwesome6", name: "atom" },
      { type: "FontAwesome6", name: "globe" },
      { type: "FontAwesome6", name: "calculator" },
    ],
  },
  {
    groupName: "Family",
    icons: [
      { type: "FontAwesome6", name: "users" },
      { type: "FontAwesome6", name: "cat" },
      { type: "FontAwesome6", name: "baby" },
      { type: "FontAwesome6", name: "child" },
      { type: "MaterialCommunityIcons", name: "human-female" },
      { type: "MaterialCommunityIcons", name: "human-male" },
      { type: "MaterialCommunityIcons", name: "family-tree" },
      { type: "FontAwesome6", name: "people-arrows" },
    ],
  },
];

export default ICONS_DATA;
